# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J8jxm1tS8yZLF_jy4v8MFuZ5XS6k7xS3
"""

import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau, CSVLogger, TensorBoard
from runner import *
from trainer import *
from data_provider import *
from custom_metrics import *
from custom_losses import *
import os
import random
from tensorflow.keras.layers.experimental import preprocessing
import numpy as np
from keras.models import Model
from keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D
from keras.layers import BatchNormalization
from keras.layers import Add
from keras.layers.core import SpatialDropout2D, Activation
from tensorflow.keras.applications import EfficientNetB0
from keras import backend as K
from keras.layers.merge import concatenate
from keras.utils.data_utils import get_file
from tensorflow import keras
#from yolov3_model import *
from yolox_model import *


class yolov3():
  def build_model(self):
    model = YoloV3(size=416, channels=3, anchors=yolo_anchors, masks=yolo_anchor_masks, classes=3, training=True)
    return model

   
class yoloxmy():
  def build_model(self):
    model = myyolox()
    return model


class myyolo_convres():
  def build_model(self):
    model = myconv_res()
    print(model.summary())
    return model


class myyolo_convres_darknet():
  def build_model(self):
    model = myconv_res_darknet()
    print(model.summary())
    return model


class myyolo_convres_leaky_relu_bn():
  def build_model(self):
    model = myconv_res_leaky_relu_bn()
    print(model.summary())
    return model

    