# -*- coding: utf-8 -*-
"""runner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DaB4jTYv1eTC7IZAnFcA6kOgChdWOjTM
"""

import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau, CSVLogger, TensorBoard
from tensorflow.keras.optimizers import Adam
from dataclasses import dataclass
from trainer import *
from data_provider import *
from custom_models import *
from custom_metrics import *
from custom_losses import *
import os
import random
from tensorflow.keras.layers.experimental import preprocessing 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import albumentations as A
import numpy as np
from keras.models import Model
from keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D
from keras.layers import BatchNormalization
from keras.layers.core import SpatialDropout2D, Activation
from tensorflow.keras.applications import EfficientNetB0
from keras import backend as K
from keras.layers.merge import concatenate
from keras.utils.data_utils import get_file
from tensorflow import keras
import cv2
import datetime
import pickle


def runner(data_provider_obj, trainer_obj):
  train_data = data_provider_obj.get_train()
  val_data = data_provider_obj.get_val()
  trainer_obj.train(train_data, val_data)


