# -*- coding: utf-8 -*-
"""utils.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/174i-5fGudbtTWoPjgQHcOoBPD-7pSetz
"""



def make_wandb_config(cur_params):
  cfg_train_dataset = str(cur_params['input_train_dataset'])
  cfg_val_dataset = str(cur_params['input_val_dataset'])
  cfg_classes = str(cur_params['input_classes'])
  cfg_image_size = str(cur_params['input_image_size'])
  cfg_batch_size = str(cur_params['input_batch_size'])
  cfg_yolo_max_boxes = str(cur_params['input_yolo_max_boxes'])    
  cfg_num_grid_cell = str(cur_params['input_num_grid_cell'])
  cfg_buffer_size = str(cur_params['input_buffer_size'])
  cfg_model_obj = str(cur_params['input_model_obj'])
  cfg_optimizer = str(cur_params['input_optimizer'])
  cfg_loss = str(cur_params['input_loss'])
  cfg_metrics = str(cur_params['input_metrics'])
  cfg_epochs = str(cur_params['input_epochs'])
  cfg_net_info_path = str(cur_params['net_info_path'])
  cfg_model_checkpoints_path = str(cur_params['model_checkpoints_path'])
  cfg_callbacks = str(cur_params['input_callbacks'])
  wandb_config={"train_dataset": cfg_train_dataset,
          "val_dataset": cfg_val_dataset,
          "classes": cfg_classes,
          "image_size": cfg_image_size,
          "batch_size": cfg_batch_size,
          "yolo_max_boxes": cfg_yolo_max_boxes,
          "num_grid_cell": cfg_num_grid_cell,
          "buffer_size": cfg_buffer_size,
          "model_obj": cfg_model_obj,
          "optimizer": cfg_optimizer,
          "loss": cfg_loss,
          "metrics": cfg_metrics,
          "epochs": cfg_epochs,
          "net_info_path": cfg_net_info_path,
          "model_checkpoints_path": cfg_model_checkpoints_path,
          "callbacks": cfg_callbacks,
                 }
  return wandb_config